### ISSUE TITLE
Support Hyper.sh as backend driver

### ISSUE THREAD

**Issue by Gnep** [alexellis/jaas#10]
Hyper.sh as backend driver

## Expected Behavior

It would be great to support Hyper.sh or ACI as backend driver

## Current Behavior

Need a VM cluster 

## Possible Solution

Hyper.sh API is consistent with Docker.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Ad-hoc jobs without infrastructure, per-second billing

## Your Environment

* Version used:
* Environment name and version (e.g. Docker 1.13):
* Server type and version:
* Operating System and version:
* Link to your project: hyper.sh

**Comment by alexellis** [comment]
Are you offering to do the work for this?

I think this request might be more pertinent for http://github.com/alexellis/faas

**Comment by Gnep** [comment]
What's the difference between faas and jaas?

**Comment by alexellis** [comment]
Are the Readme files useful?
JaaS is a utility for Docker Swarm tasks. OpenFaas is -> www.openfaas.xom

**Comment by alexellis** [comment]
*.com

**Comment by Gnep** [comment]
Hi Alex,

Maybe I should change my question: Is JaaS an open connector for both high-level application to consume and backend engine to integrate with?

I'm looking at to integrate Hyper.sh with Cog (https://github.com/operable/cog), e.g. Serverless ChatOps. JaaS is the perfect middleware for this purpose. What do you think?

**Comment by alexellis** [comment]
Let's get onto a quick call so I can explain the difference between JaaS and OpenFaaS for some high level detail. Can you email me on LinkedIn or alex@openfaas.com?

**Comment by alexellis** [comment]
Closing as inactive.
