### ISSUE TITLE
Feature: Support swarm secrets

### ISSUE THREAD

**Issue by alexellis** [alexellis/jaas#14]
Pre-existing secrets should be able to be referenced from the JaaS task

## Expected Behavior

```
jaas run --secret oauth_token --secret developer_token alexellis2/github:scrape
```

## Current Behavior

Secrets are not supported.

## Possible Solution

Write code for this feature.

**Comment by alexellis** [comment]
@IkeLutra Will - checkout the refactoring in 0.2.0.. do you want to work on this feature?

**Comment by IkeLutra** [comment]
@alexellis Yeah sure will take a look

**Comment by alexellis** [comment]
I would think you could re-use all or parts of the OpenFaaS codebase - https://github.com/openfaas/faas-swarm/blob/master/handlers/deploy.go#L252

**Comment by IkeLutra** [comment]
@alexellis Do we want to support the expanded syntax  e.g. `--secret source=app-key,target=app,uid=1000,gid=1001,mode=0400`
 (https://docs.docker.com/engine/reference/commandline/service_create/#create-a-service-with-secrets)?

Also do we want `--secrets="secret1,secret2"` or `--secret secret1 --secret secret2`. My preference is the second one so it is consistent with `docker service` and `faas-cli`. What do you think?

**Comment by alexellis** [comment]
So I'd suggest `--secret secret-name1` `--secret secret-name2` to keep it simple. Extended syntax is probably not necessary for batch jobs.

**Comment by ceejatec** [comment]
FWIW, extended syntax would be very handy. However I'd be happy with just basic secret support also.

**Comment by alexellis** [comment]
@IkeLutra @ceejatec do either of you want to work on this?

**Comment by alexellis** [comment]
Derek add label: help wanted

**Comment by MarcPer** [comment]
I created a PR for this, but I followed the syntax defined by `--mount`, which is `--secret secret_name=secret_file` so the project is self-consistent. I don't mind changing it, if necessary.

Regarding the style, I didn't find any guidelines, but I tried to follow the code I saw. Please let me know if something could be improved.

Finally, regarding tests, I saw that the code is mostly untested, so I didn't add tests either. Maybe it would be a good idea to increase the coverage, adding tests for all flags. I would say this could be done in a separate PR.

I did update the documentation, though.

**Comment by alexellis** [comment]
@MarcPer The code is fully tested, but not with unit tests. If you have time to add unit tests, then please go ahead, but raise a separate issue first. As per the thread please stick to the `--secret name-of-secret` syntax and see if this works as expected. I can't see a need for the extended syntax for the use-cases I've seen so far with `jaas`. 

Alex

**Comment by MarcPer** [comment]
Should this issue be closed? The PR was already merged.

**Comment by alexellis** [comment]
Derek close

**Comment by alexellis** [comment]
Yes 👍
