### ISSUE TITLE
Job waits timeout on task failure

### ISSUE THREAD

**Issue by WTFKr0** [alexellis/jaas#17]
Note: Maybe it's an expected behavior

## Expected Behavior

I think the job may finish as soon as the task is terminated to get logs and RC

## Current Behavior

The job waits timeout if the task finish early with error code != 0

## Possible Solution

Break the wait loop if the status is like `"State":"failed"`

## Steps to Reproduce (for bugs)

Job with RC 0 OK:
`echo -e 'FROM alpine\nCMD ["ls"]' | docker build -t wtf - && ./jaas run -r -i wtf`
Job with RC != 0, waits 60 ticks:
`echo -e 'FROM alpine\nCMD ["ls","bad"]' | docker build -t wtf - && ./jaas run -r -i wtf`

## Context

Just testing !

## Your Environment

* Version used: commit afb552b70765da81507b67954618a4988ff2f551
* Environment name and version (e.g. Docker 1.13): docker 17.09.0-ce

**Comment by alexellis** [comment]
Good find! 😃 I'll sort it out after work.. any other comments, suggestions or questions?

**Comment by WTFKr0** [comment]
Sure ! Will come in future issues when i found them ! :whale:

**Comment by alexellis** [comment]
I've updated the code now.. can you try again and also would you like to join my slack community?
