### ISSUE TITLE
Feature: Add env file support

### ISSUE THREAD

**Issue by IkeLutra** [alexellis/jaas#27]
## Expected Behavior
`jaas run --env-file .env -image alexellis2/href-counter:latest`
## Current Behavior
Currently if you have a number of environment variables you need to specify them all on the command line. 

## Possible Solution
Currently working copy here: https://github.com/IkeLutra/jaas/tree/addEnvFileSupport

Issues with this solution are:
- Imports all of docker cli for one function (could use https://github.com/joho/godotenv instead for parsing envfile)
- Some code has been copied from docker/cli repo (Are licenses compatible? or should it just be rewritten?)

Advice would be appreciated.

## Context
I have a couple of images which I pass up to 10 environment variables to. Would be simpler to use a .env file so I don't have to copy and paste them when ever I run jaas commands.

**Comment by alexellis** [comment]
Let's write this from scratch, there's no sense in vendoring all that code for what is just a string split operation. You can copy some of the code from the FaaS-CLI project if that helps.

**Comment by IkeLutra** [comment]
Makes sense. Will investigate the FaaS-CLI later and rewrite my implementation.

**Comment by alexellis** [comment]
Hey @IkeLutra are you good to go with this? Do you want an invitation to Slack where we have a #jaas channel? @ddingel is there too and @dungeonmaster18 (who have contributed)

**Comment by alexellis** [comment]
Fixed in master.. please pull, build and try it out.

```
alext:jaas alex$ cat > envfile.txt
a=b
alext:jaas alex$ go build && ./jaas run -r --image alpine:3.6 --command "env" --env-file=./envfile.txt
Service created: angry_goodall (y4h3jbszgqwwuap2mb8oyjjrp)
ID:  y4h3jbszgqwwuap2mb8oyjjrp  Update at:  2018-02-06 13:52:36.796714488 +0000 UTC
........

Exit code: 0
State: complete


Printing service logs
a2018-02-06T13:52:40.743015179Z PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
52018-02-06T13:52:40.743060180Z HOSTNAME=e69900d1c93a
#2018-02-06T13:52:40.743069670Z a=b
*2018-02-06T13:52:40.743072258Z HOME=/root

Removing service...
```

**Comment by alexellis** [comment]
Fixed in master.. please pull, build and try it out.

```
alext:jaas alex$ cat > envfile.txt
a=b
alext:jaas alex$ go build && ./jaas run -r --image alpine:3.6 --command "env" --env-file=./envfile.txt
Service created: angry_goodall (y4h3jbszgqwwuap2mb8oyjjrp)
ID:  y4h3jbszgqwwuap2mb8oyjjrp  Update at:  2018-02-06 13:52:36.796714488 +0000 UTC
........

Exit code: 0
State: complete


Printing service logs
a2018-02-06T13:52:40.743015179Z PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
52018-02-06T13:52:40.743060180Z HOSTNAME=e69900d1c93a
#2018-02-06T13:52:40.743069670Z a=b
*2018-02-06T13:52:40.743072258Z HOME=/root

Removing service...
```

**Comment by IkeLutra** [comment]
@alexellis Thanks for sorting that. I have had a manic couple of weeks so not had a chance to look at it.

Yeah slack invite would be great thanks.

**Comment by alexellis** [comment]
Just email me alex@openfaas.com
