### ISSUE TITLE
Feature: Add ability to specify command

### ISSUE THREAD

**Issue by IkeLutra** [alexellis/jaas#28]
## Expected Behavior
`jass --image bash --command ls -lha /`

## Current Behavior
Currently not possible to specify the command that you want the service to run.

## Possible Solution
Will need the Command field adding to the ContainerSpec. Have started this but couldn't get it to work yet.

## Context
I have a docker container that wraps a CLI program which has a signature like `my_command process` and `my_command test`. When I run using docker run `docker run my_command_image process`. My current work around is to modify the CLI script to use an environment variable but would be simpler to be able to specify the command. The other workaround would be to have specific docker images for each command but that adds a lot more work.

Let me know your thoughts? My two suggestions feel like we are duplicating more and more of the docker API which maybe is a bad thing? 🤷‍♂️

**Comment by alexellis** [comment]
If we can do it through the container/service or task spec then I don't mind.. we'd just add another parameter to "jaas run" 👍

**Comment by alexellis** [comment]
This is merged.. please check it out @IkeLutra
