### ISSUE TITLE
ENHANCEMENT : Follow logs tail style

### ISSUE THREAD

**Issue by sbrouet** [alexellis/jaas#38]
Hello,

## Current Behavior
In current version, the logs are displayed once the service has terminated
While the service is executing, the Jaas command only outputs some dots 

For example:

"
[truncated output]
Service created: vibrant_mcclintock (4p4vy93tij38fhbxqyrgp6rt8)
ID:  4p4vy93tij38fhbxqyrgp6rt8  Update at:  2018-11-08 15:47:32.340267998 +0000 UTC
...

Exit code: 0
State: complete

Printing service logs
$2018-11-08T15:47:33.547861076Z dummy
"

The command executed was "echo dummy"

## Possible Solution
It would be nice having a "--follow" option in the style of "tail" or other utilities, so the logs are streamed to the standard output and displayed in tools that launch the Jaas command

## Steps to Reproduce (for bugs)
Not really a bug, but here is how I launch the command :
/root/jaas run -t=120s --remove=true --show-logs=true --verbose=true --image ubuntu:latest --command "echo dummy"

## Context
Trying to use Jaas as a way of launching batch containers synchronously on a Swarm cluster.
The “synchronously” word is important, I am running these containers from a Jenkins instance, and which that the Jenkins Job does stream the container’s logs to the standatd output and stops when the container has stopped.

Thank you for your help / advice

**Comment by alexellis** [comment]
No, not right now. You'll need to run `docker service logs` in a separate window.
