### ISSUE TITLE
Feature request: Support service placement constraints

### ISSUE THREAD

**Issue by johnharris85** [alexellis/jaas#4]
Would be useful to be able to specify that ad-hoc jobs should only happen on specific nodes (using existing service `--constraint` syntax?). For example, some task should happen on all database nodes, or all RHEL nodes, etc...

**Comment by alexellis** [comment]
That is probably a good addition. 👍

**Comment by alexellis** [comment]
Did you want to take a stab at this?

**Comment by alexellis** [comment]
This is fixed and released - thanks @ddingel.
