### ISSUE TITLE
Feature request: Specify network

### ISSUE THREAD

**Issue by amoljimber** [alexellis/jaas#40]
I would like to be able to join the service/container with a specific overlay network, am I already able to do this?

**Comment by alexellis** [comment]
I think that's already supported, if not please raise a PR.

Alex

**Comment by alexellis** [comment]
https://github.com/alexellis/jaas/blob/6adc0bed947ffdb5a73836184381773cf7e162d9/cmd/run.go#L34

Can confirm this is available. I'll close the issue
