### ISSUE TITLE
Idea: add supports to env-file

### ISSUE THREAD

**Issue by sanslash332** [alexellis/jaas#47]
As the classic service create command supports the --env-file argument to pass a file to load various env vars at time, add that option on jaas.

 
## Expected Behavior

simply you can have a file like that:
```bash
var=foo
ver=fii
```
named env.env

so you can do:

jaas --env-file env.env -r local/myImage
## Current Behavior

Currently you have to do that in a single line, and if you are testing or you have to call the command with a lot of envVars, could be a less readable line.

jaas -r -e var=foo -e ver=fii local/myimage

## Context

I want to use jaas in a gitlab_ci job. The jaas excecution is inside a template, so I only want have to put all my vars in a env.file, and the template can handle the task, only passing to the jaas the env file.

Thanks!

Very awesome project!

**Comment by alexellis** [comment]
Thanks for using JaaS. 

I'd be open to a contribution for this, alternatively, if your company wants to become a GitHub Sponsor at the business level, I'd be open to prioritising it for you. https://github.com/sponsors/alexellis

**Comment by sanslash332** [comment]
I saw on the jaas --help command, that the --env-file parameter is supported.

Please, add it on the readme.MD documentation, to check it at the first read that is supported 😄 
Thanks for this awesome tool. 😉

**Comment by alexellis** [comment]
Understood. I will think about adding it on the readme.

As a commercial user of jaas, please consider supporting the tool, if you want me to keep developing it.

https://github.com/sponsors/alexellis
