### ISSUE TITLE
question: how use authentication for v2 registries

### ISSUE THREAD

**Issue by sanslash332** [alexellis/jaas#48]
hello guys, is a small question; what is the correct way to pass a registry token to the jaas when the token is for a v2 registry?

After log-in to the registry with the docker login command, the result in config.json file have this schema:

{
        "auths": {
                "my.registry.domain": {
                        "auth": "ALargeStringWithData"
                }                                                                                                       
        },                                                                                                              
        "HttpHeaders": {                                                                                                
                "User-Agent": "Docker-Client/19.03.12 (linux)"                                                          
        }                                                                                                               

I don't know with value I have to pass to the --registry flag. Is the entire file encoded in base64? only the large string under the domain key? Or the same value but encripted?

Thanks guys 😄 😃

**Comment by alexellis** [comment]
Hi, it should be no different to how I listed it in the README.

https://github.com/alexellis/jaas

Happy for you to book a paid 1:1 Zoom call with me if you want a demo? 

Less than 5 employees (small business rate)
https://calendly.com/alexellis/small-business-consultation?back=1

Rate for more than 5 employees:
https://calendly.com/alexellis/50min-stripe?back=1

**Comment by sanslash332** [comment]
Um, is rare.

I tried using directly the string at auths.servername.auth, but didn't work, and next I tried using the manual method listed on the readme, with converting the json file to base64.

But, when i passed that base64 string to jaas, it says service created (with any other ouptut) and returns a code 25 instead to said any other thing.

In other cases when i've tried pass the authentication with any other option, the service isnt created and falls in to a regected state, because cand find the image on my registry.

But if you launch a classic
docker service create --with-auth-registry my.server.registry/folder/image the code works.

Mayve is a problem with the image url?

Is a image hosted on a Harbor registry.

Is possible have more debug output from jaas? i've tried with the -b or --verbose flags, but dont give to me more information.

thanks for your fast answer 😄 
@alexellis

**Comment by sanslash332** [comment]
Hello @alexellis well thanks for your support and feedback.

Finally works for me a plain authentication onli with {"username": "user", "password": "passowrd"} and encrypt it with base64

The extrange is with a large password including special symbols, with various random characters, the encoding didn't work and the jaas run returns code 25, but... well.

Again thanks for your feedback, and sorry for my constant silly questions.
