### ISSUE TITLE
Feature request: ATA for parsing secret 

### ISSUE THREAD

**Issue by wannaknowmo** [alexellis/jaas#5]
hi Alex,
do you have an ATA for parsing secret?

thank you

**Comment by alexellis** [comment]
I am not sure what an ATA is. Can you explain?

Please can you fill out the provided template too?

**Comment by wannaknowmo** [comment]
in your roadmap you mention  about  "Support optional secrets through CLI
flag"
i probably misunderstood the meaning of secrets :-(
are you talking about docker secret api or how to parse a secret as a
hidden variable to a container?

ATA means actual time of arrival, it was referring to your roadmap.

thanks

-Alexandre

**Comment by alexellis** [comment]
This would be for Docker swarm secrets. You can define them through the Docker CLI on your swarm, but JaaS won't consume them yet. It could be made to.. if you need it?

**Comment by alexellis** [comment]
Closing as inactive.
