### ISSUE TITLE
Feature request: get Exit Code from swarm task 

### ISSUE THREAD

**Issue by wannaknowmo** [alexellis/jaas#6]
would it be possible to get back the return code of whatever you ran in the container into a jaas variable?

**Comment by alexellis** [comment]
I think that could be possible. Can you give me a use-case / example to test with?

**Comment by wannaknowmo** [comment]
basically when i start a program with jaas, i'm always getting a return
code 0

wanted to know if you could return the return code from whatever ran inside
the container?

if not that's ok it could be track inside the container to an external db .

we are using jaas combine with docker/ansible/walter to start multiple
environments so far it works great!!!.


[root@XXXX /var/docker/coucou]# docker run -e CMD="ls" -it coucou ;echo $?

bin   dev  home  lib64       media  opt   root  sbin  sys  usr

boot  etc  lib   lost+found  mnt    proc  run   srv   tmp  var
0

[root@XXXX/var/docker/coucou]# docker run -e CMD="lss" -it coucou ;echo $?

/bin/sh: lss: command not found

127

[root@XXXX/var/docker/coucou]# jaas --env CMD="lss" -image coucou --timeout
3;echo $?

Service created: brave_euclid (x2q8l0zwh2agef9uwc7090axb)

ID:  x2q8l0zwh2agef9uwc7090axb  Update at:  2017-04-14 00:11:49.061227139
+0000 UTC

...Timing out after 3 ticks.0


thank you

-Alexandre

**Comment by alexellis** [comment]
Makes total sense and really glad you're finding JaaS useful.

You might also like my Functions as a Service framework which works in a similar way to this project, but has a UI and more more active development. http://github.com/alexellis/faas

I've push a change up for the exit codes. 

To test it you'll just need to go into the `go/src/github.com/docker/docker` project and do a `git pull`.

```
./jaas -image alexellis2/href-counter:latest --env url=http://blog.alexellis.io/ --showlogs=true --timeout=2 --rm; echo $?
Service created: compassionate_meitner (ylvzyq56qgdfz9nlj9j20nslc)
ID:  ylvzyq56qgdfz9nlj9j20nslc  Update at:  2017-04-14 07:20:30.142078522 +0000 UTC
..Timing out after 2 ticks.26
```

**Comment by wannaknowmo** [comment]
i do not see any jaas file after the git pull

[root@XXX ~/go/src/github.com/docker/docker]# find . -name "*jaas*"

[root@XXX ~/go/src/github.com/docker/docker]#

**Comment by alexellis** [comment]
You're in the wrong directory there.. you should be in $GOPATH/src/github.com/alexellis/jaas - then do go build`. @wannaknowme

**Comment by alexellis** [comment]
This is fixed/active now.
