### ISSUE TITLE
Publish to docker hub

### ISSUE THREAD

**Issue by byrnedo** [alexellis/jaas#8]
Hi, Is there a published image for this?

**Comment by alexellis** [comment]
Yes it's alexellis2/jaas as a manual build, it's swapping over to auto-build though: https://hub.docker.com/r/alexellis2/jaas

**Comment by aeons** [comment]
Looks like auto-build is not working any more.

**Comment by alexellis** [comment]
Hi @aeons are you using `jaas`?

I'll trigger a commit by pushing some code, let's see if that works, otherwise I'd be happy to accept a PR to build with Travis following the pattern in faas-cli.

Alex

**Comment by aeons** [comment]
Yeah, I want to run a cron job against a docker swarm, and that is apparently really hard. `jaas` seems to solve it nicely.

**Comment by alexellis** [comment]
Check out the tag which was pushed by the Hub just now.
